<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
  targetNamespace="http://www.arkivverket.no/standarder/nha/avlxml/avlsup"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:avlmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
  xmlns:supmdk="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
  elementFormDefault="qualified">

  <xs:import namespace="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk"
    schemaLocation="avlxml-mdk.xsd"/>
  <xs:import namespace="http://www.arkivverket.no/standarder/nha/avlxml/avlsup-mdk"
    schemaLocation="avlsup-mdk.xsd"/>

  <xs:element name="avlsup" type="supplerendeopplysninger"/>

  <xs:complexType name="supplerendeopplysninger">
    <xs:annotation>
      <xs:documentation>
        Supplerende opplysninger er en egen datastruktur som angir metadata knyttet til avleverte dokumenter. 
      </xs:documentation>
      <xs:documentation>
        For hver pasient etableres det en fil med supplerende opplysninger per dokument.
      </xs:documentation>
      <xs:documentation>
        Hvert dokument kobles til pasientjournalen ved hjelp av journalidentifikatoren som er benyttet for pasienten.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="dokument" type="dokument"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="dokument">
    <xs:annotation>
      <xs:documentation>
        Denne klassen gjentas for hvert dokument i pasientjournalen.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="dokumentidentifikator" type="supmdk:dokumentidentifikator"/>
      <xs:element name="journalidentifikator" type="avlmdk:journalidentifikator"/>
      <xs:element name="filsti" type="supmdk:filsti"/>
      <xs:element name="dokumenttype" type="dokumenttype"/>
      <xs:element name="dokumentdato" type="supmdk:dokumentdato"/>
      <xs:element maxOccurs="unbounded" name="Organisasjon" type="Organisasjon"/>
      <xs:element minOccurs="0" name="episode" type="episode"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="diagnose" type="diagnose"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="prosedyre" type="prosedyre"/>
      <xs:element minOccurs="0" name="henvisningsperiode" type="henvisningsperiode"/>
      <xs:element minOccurs="0" name="behandlendeAvdeling" type="behandlendeAvdeling"/>
      <xs:element minOccurs="0" name="saksnummer" type="supmdk:saksnummer"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="dokumenttype">
    <xs:annotation>
      <xs:documentation>
        Denne klassen beskriver dokumenttype.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="dokumenttypeKode" type="supmdk:dokumenttypeKode"/>
      <xs:element name="dokumenttypeTekst" type="supmdk:dokumenttypeTekst"/>
      <xs:element name="dokumenttypeKodeverk" type="supmdk:dokumenttypeKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Organisasjon">
    <xs:annotation>
      <xs:documentation>
        Denne klassen inneholder opplysninger om organisasjonen(e) som har lagt inn informasjon i dokumentet.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="organisasjonNummer" type="avlmdk:organisasjonsnummer"/>
      <xs:element name="organisasjonNavn" type="avlmdk:foretaksnavn"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="episode">
    <xs:annotation>
      <xs:documentation>
        Denne klassen benyttes for dokumenter som er tilknyttet en episode.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="episodeId" type="supmdk:episodeID"/>
      <xs:element name="episodeStartdato" type="supmdk:episodeStartdato"/>
      <xs:element name="episodeSluttdato" type="supmdk:episodeSluttdato"/>
      <xs:element name="omsorgsniva" type="omsorgsniva"/>
      <xs:element name="fagomrade" type="fagomrade"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="omsorgsniva">
    <xs:annotation>
      <xs:documentation>
        Denne klassen beskriver omsorgsnivå på episoden. Omsorgsnivå angir om behandlingen er gitt ved innleggelse, dagbehandling eller poliklinikk.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="omsorgsnivaKode" type="supmdk:omsorgsnivaKode"/>
      <xs:element name="omsorgsnivaKodetekst" type="supmdk:omsorgsnivaKodetekst"/>
      <xs:element name="omsorgsnivaKodeverk" type="supmdk:omsorgsnivaKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="fagomrade">
    <xs:annotation>
      <xs:documentation>
        Denne klassen beskriver hvilket fagområde episoden tilhører.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="fagomradeKode" type="supmdk:fagomradeKode"/>
      <xs:element name="fagomradeKodetekst" type="supmdk:fagomradeKodetekst"/>
      <xs:element name="fagomradeKodeverk" type="supmdk:fagomradeKodeverk"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="diagnose">
    <xs:annotation>
      <xs:documentation>
        Denne klassen inneholder hver enkelt diagnose som er tilknyttet dokumentet.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="diagnoseKode" type="avlmdk:diagnosekode"/>
      <xs:element name="diagnoseKodetekst" type="avlmdk:diagnosetekst"/>
      <xs:element name="diagnoseKodeverk" type="avlmdk:diagnosekodeverk"/>
      <xs:element name="diagnoseDato" type="avlmdk:diagnosedato"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="prosedyre">
    <xs:annotation>
      <xs:documentation>
        Denne klassen beskriver prosedyre(ne) som har blitt gjennomført i forbindelse undersøkelse beskrevet i et dokument.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="prosedyreKode" type="supmdk:prosedyreKode"/>
      <xs:element name="prosedyreKodetekst" type="supmdk:prosedyreKodetekst"/>
      <xs:element name="prosedyreKodeverk" type="supmdk:prosedyreKodeverk"/>
      <xs:element name="prosedyreDato" type="supmdk:prosedyreDato"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="henvisningsperiode">
    <xs:annotation>
      <xs:documentation>
        Denne klassen beskriver henvisningsperiden dokumentet er tilknyttet.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="henvisningsperiodeId" type="supmdk:henvisningsperiodeId"/>
      <xs:element name="henvisningsperiodeStartdato" type="supmdk:henvisningsperiodeStartdato"/>
      <xs:element name="henvisningsperiodeSluttdato" type="supmdk:henvisningsperiodeSluttdato"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="behandlendeAvdeling">
    <xs:annotation>
      <xs:documentation>
        Denne klassen angir hvilken avdeling som var ansvarlig for behandlingen dokumentet beskriver.
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="behandlendeAvdelingReshId" type="supmdk:behandlendeAvdelingReshID"/>
      <xs:element name="behandlendeAvdelingNavn" type="supmdk:behandlendeAvdelingNavn"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
