<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk" elementFormDefault="qualified" targetNamespace="http://www.arkivverket.no/standarder/nha/avlxml/avlxml-mdk" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="arkivskaper">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.1</xs:documentation>
            <xs:documentation>A-05, P-03</xs:documentation>
            <xs:documentation>
        A-05: Navnet på den behandlende enhet som er eller antas å ha vært arkivskaper.
      </xs:documentation>
            <xs:documentation>
        P-03: Navnet på den behandlende enhet som er eller antas å ha vært arkivskaper.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="avleveringsbeskrivelse">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.2</xs:documentation>
            <xs:documentation>A-03</xs:documentation>
            <xs:documentation>
        Tekstlig beskrivelse av den aktuelle avleveringen.
        Typisk beskrivelse av serie, periode eller annen avgrensning.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="avleveringsidentifikator">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.3</xs:documentation>
            <xs:documentation>A-02</xs:documentation>
            <xs:documentation>
        En unik identifikator tildelt av Norsk helsearkiv ved inngåelse av avtale om avlevering. (OID-format)
        Siden en avtale kan beskrive flere uavhengige avleveringer, er denne ikke den samme som avtaleidentifikatoren.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+.)+([0-9]+)|inc[0-9]+" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="avlxmlversjon">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.4</xs:documentation>
            <xs:documentation>A-01</xs:documentation>
            <xs:documentation>
        Spesifikasjonens versjonsnummer uttrykt i OID-formatet.
        Avleveringer som følger denne versjonen av spesifikasjonen, skal ha versjonsidentifikator "2.16.578.1.39.100.5.2.4".
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="2.16.578.1.39.100.5.2.4" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="avtalebeskrivelse">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.5</xs:documentation>
            <xs:documentation>A-08</xs:documentation>
            <xs:documentation>
        Tekstlig beskrivelse av den aktuelle avtalen.
        Typisk innhold vil være kort beskrivelse av virksomheten og hvilket arkiv, omfang og periode avtalen skal omfatte.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="avtaledato">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.6</xs:documentation>
            <xs:documentation>A-07</xs:documentation>
            <xs:documentation>Den dato avtalen referer seg til.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="avtaleidentifikator">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.7</xs:documentation>
            <xs:documentation>A-06</xs:documentation>
            <xs:documentation>
        En unik identifikator tildelt av Norsk helsearkiv ved inngåelse av avtale om avlevering. (OID-format).
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]+.)+([0-9]+)" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="diagnosedato">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.8</xs:documentation>
            <xs:documentation>D-01, D-08</xs:documentation>
            <xs:documentation>
        D-01: Dato tilknyttet diagnosen slik den er anført i pasientjournalen, eller år dersom bare årstall er kjent.
      </xs:documentation>
            <xs:documentation>
        D-08: Dato diagnosen er satt
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="diagnosekode">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.9</xs:documentation>
            <xs:documentation>D-02, D-05</xs:documentation>
            <xs:documentation>
        D-02: Diagnosekoden slik den er anført i pasientjournalen.
        (f.eks. "037" når dette er hentet fra ICD9 benyttet i perioden 1987-1998).
      </xs:documentation>
            <xs:documentation>
        D-05: Diagnosekoden som er tilknyttet dokumentet.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="diagnosetekst">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.10</xs:documentation>
            <xs:documentation>D-03, D-06</xs:documentation>
            <xs:documentation>
        D-03: Diagnoseteksten slik den er anført i pasientjournalen (f.eks. "Stivkrampe").
      </xs:documentation>
            <xs:documentation>
        D-05: Tekstlig beskrivelse av diagnosen.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="diagnosekodeverk">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.11</xs:documentation>
            <xs:documentation>D-04, D-07</xs:documentation>
            <xs:documentation>
        D-04: Dersom diagnosekode er brukt skal det angis hvilket diagnosekodeverk som diagnosekoden er hentet fra.
        Dette vil i de fleste tilfeller omfatte forskjellige versjoner av ICD-kodeverk, og følgende verdier skal da benyttes:
          ICD7: 2.16.578.1.12.4.1.1.7122
          ICD8: 2.16.578.1.12.4.1.1.7121
          ICD9: 2.16.578.1.12.4.1.1.7120
          ICD10: 2.16.578.1.12.4.1.1.7110
        Dersom kodeverket er ukjent, benyttes verdi 0.
      </xs:documentation>
            <xs:documentation>
        D-07: Kodeverk som diagnosekoden er hentet fra.
        Hvis det er et lokalt kodeverk, må dette kodeverket legges ved som dokumentasjon i avleveringen.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(0|([0-9]+.)+([0-9]+))" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="fanearkidentifikator">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.12 </xs:documentation>
            <xs:documentation>P-02</xs:documentation>
            <xs:documentation>
        Dersom det er gjort avtale om innlegg av faneark i den fysiske pasientjournalen med sikte på senere digitalisering,
        skal denne identifikatoren registreres fra det aktuelle fanearket som legges i journalen.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="fodselsnummer">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.13</xs:documentation>
            <xs:documentation>P-07</xs:documentation>
            <xs:documentation>
        Pasientens fødselsnummer dersom det finnes eller er kjent jf. helsearkivforskriften § 23 annet ledd punkt a.
        Også nasjonal D-nummer eller virksomhetsinterne H-nummer kan registreres dersom pasientens fødselsnummer ikke er kjent.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="fodtdato">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.14</xs:documentation>
            <xs:documentation>P-09</xs:documentation>
            <xs:documentation>
        Pasientens fødselsdato, eller fødselsår dersom bare årstall er kjent.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="forstekontakt">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.15</xs:documentation>
            <xs:documentation>P-13</xs:documentation>
            <xs:documentation>Pasientens første kontaktdato/år i journalen</xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="journalidentifikator">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.16</xs:documentation>
            <xs:documentation>P-01, S-02</xs:documentation>
            <xs:documentation>
        P-01: Identifikator for pasientjournalen som er garantert unik innenfor denne avleveringen.
        (UUID anses som en velegnet identifikator for dette formålet og bør benyttes om mulig.)
      </xs:documentation>
            <xs:documentation>
        S-02: Identifikator som er benyttet for pasienten man etablerer supplerende opplysninger for.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="journalnummer">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.17</xs:documentation>
            <xs:documentation>P-06</xs:documentation>
            <xs:documentation>
        Kan benyttes til å registrere journalnummer dersom det finnes.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="kjonn">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.18</xs:documentation>
            <xs:documentation>P-12</xs:documentation>
            <xs:documentation>Pasientens kjønn (M, K, U)</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="M" />
            <xs:enumeration value="K" />
            <xs:enumeration value="U" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="lagringsenhet">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.19</xs:documentation>
            <xs:documentation>P-04</xs:documentation>
            <xs:documentation>
        En kodet verdi som identifiserer den aktuelle lagringsenhet (boks) som inneholder den fysiske pasientjournalen.
        Det kan registreres flere verdier tilknyttet samme pasientjournal dersom denne er så omfangsrik at den må avleveres i flere lagringsenheter.
        Verdier og koder som benyttes bør avklares med Norsk helsearkiv i avtaleprosessen.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="lopenummer">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.20</xs:documentation>
            <xs:documentation>P-05</xs:documentation>
            <xs:documentation>
        Kan benyttes til å registrere løpenummer dersom det finnes.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="merknad">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.21</xs:documentation>
            <xs:documentation>P-15</xs:documentation>
            <xs:documentation>
        Dette feltet skal kun brukes etter avtale med Norsk helsearkiv.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="morsdato">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.22</xs:documentation>
            <xs:documentation>P-10</xs:documentation>
            <xs:documentation>
        Pasientens dødsdato, eller år dersom bare årstall er kjent.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="pasientnavn">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.23</xs:documentation>
            <xs:documentation>P-08</xs:documentation>
            <xs:documentation>Pasientens fulle navn</xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="sikkermors">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.24</xs:documentation>
            <xs:documentation>P-11</xs:documentation>
            <xs:documentation>
        Dersom dødsdato/år ikke er kjent, men pasienten er bekreftet mors, skal arkivskaper bekrefte dette med en indikator (1= sikker mors, 0= ukjent morsstatus).
        Dette benyttes særlig når avlevering av pasientjournal skjer i henhold til helsearkivforskriftens § 19.
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[01]" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="sistekontakt">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.25</xs:documentation>
            <xs:documentation>P-14</xs:documentation>
            <xs:documentation>Pasientens siste kontaktdato/år i journalen.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="virksomhetsnavn">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.26</xs:documentation>
            <xs:documentation>A-10</xs:documentation>
            <xs:documentation>
        Navnet på den virksomheten som forestår avleveringen iht. foretaksnavn i Enhetsregisteret.
        (Dette kan være forskjellig fra navnet på arkivskaper i A-04)
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="ikkeTom" />
    </xs:simpleType>
    <xs:simpleType name="foretaksnavn">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.27</xs:documentation>
            <xs:documentation>A-11, O-02</xs:documentation>
            <xs:documentation>
        A-11: Navnet på det overordnede foretaket (dersom dette er forskjellig fra virksomhetsnavnet)
      </xs:documentation>
            <xs:documentation>
        O-02: Navn
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string" />
    </xs:simpleType>
    <xs:simpleType name="organisasjonsnummer">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.28</xs:documentation>
            <xs:documentation>A-09, O-01</xs:documentation>
            <xs:documentation>
        A-09: Norsk organisasjonsnummer til ansvarlig virksomhet som forestår avleveringen
      </xs:documentation>
            <xs:documentation>
        O-01: Organisasjonsnummer
      </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{9}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="generertdato">
        <xs:annotation>
            <xs:documentation>OID:2.16.578.1.39.100.1.3001.29</xs:documentation>
            <xs:documentation>A-04</xs:documentation>
            <xs:documentation>Den dato avleveringslisten ble generert</xs:documentation>
        </xs:annotation>
        <xs:restriction base="arkDATO" />
    </xs:simpleType>
    <xs:simpleType name="arkDATO">
        <xs:annotation>
            <xs:documentation>Generelt datoformat</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="(1[89][0-9]{2}|20[0-9]{2})(-(0[1-9]|1[012])(-([012][0-9]|3[01]))?)?" />
            <xs:pattern value="(1[89][0-9]{2}|20[0-9]{2})(0[1-9]|1[012])([012][0-9]|3[01])" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="ikkeTom">
        <xs:annotation>
            <xs:documentation>Generell regel for tekstfelter som ikke skal være tomme</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="collapse" />
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>